[build]
  publish = "dist"
  command = "npm run build"

[[images.remote_patterns]]
  protocol = "https"
  hostname = "images.unsplash.com"

[[images.remote_patterns]]
  protocol = "https"
  hostname = "cdn.brandfetch.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
